<?php /* Copied from https://yoast.com/privacy-policy/ */ ?>
<center><h1 class="bottom_border theme_color">Privacy policy</h1></center>
<p><?php echo get_domain_name(); ?> has created this privacy statement in order to show our commitment to your and our privacy. This page discloses the information gathering and dissemination practices for the website <?php echo get_domain_name(); ?></p>

<h4>Information Automatically Logged</h4>
<p>This website uses 'cookies', which are text files placed on your computer, to collect standard internet log information and visitor behavior information in an anonymous form. The information generated by the cookie about your use of the website (including your IP address) is saved. This information is then used to evaluate visitors use of the website and to compile statistical reports on website activity for <?php echo get_domain_name(); ?>. We will never (and will not allow any third party) use the statistical analytics tool to track or to collect any personally identifiable information of visitors to our site.</p>

<h4>Disabling and enabling cookies</h4>
<p>You have the ability to accept or decline cookies by modifying the settings on your browser.</p>

<h4>External Links</h4>
<p>This site contains (affiliate) links to some other sites. <?php echo get_domain_name(); ?> and its authors are not responsible for the privacy practices or the content of such websites.</p>

<h4>Authentication</h4>
<p>Some of our products will ask you to identify with either Google or Facebook so we can retrieve information on your behalf. We will not look at your individual data. We do reserve the right to aggregate usage data to measure the performance of our applications, but no identifiable personal information will ever be disclosed to third parties.</p>

<h4>Personal Information</h4>
<p>When you comment or subscribe to an email list, we ask for your name &amp; email address. Your email and any other information will only be used to contact you about updates on <?php echo get_domain_name(); ?>. Your personal information will not be distributed to anyone for any purpose.</p>

<h4>Security</h4>
<p>This site has security measures in place to protect the loss, misuse, and alteration of the information under our control.</p>

<h4>Contacting <?php echo get_domain_name(); ?></h4>
<p>If you have any questions about this privacy statement, the practices of this site, or your dealings with this website, you can contact us using our <a href="<?php echo site_url('contact-us'); ?>">contact form</a>.</p>
